FROM ubuntu:16.04
RUN apt-get -y update
RUN apt-get -y install python3 && apt-get install -y python3-pip
RUN pip3 install speedtest-cli
RUN pip3 install psutil
RUN pip3 install py-cpuinfo
RUN apt-get -y update && apt-get install -y net-tools 
RUN apt-get install -y iputils-ping
RUN apt-get update && apt-get install -y && apt-get -y install curl
RUN mkdir project


















































































